#!/usr/bin/env python3

import socket
import sys
import os
import datetime
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

COMMON_PORTS = {
    21: "FTP", 22: "SSH", 23: "Telnet", 25: "SMTP",
    53: "DNS", 80: "HTTP", 110: "POP3", 111: "RPC",
    135: "MSRPC", 139: "NetBIOS", 143: "IMAP", 443: "HTTPS",
    445: "SMB", 993: "IMAPS", 995: "POP3S", 1433: "MSSQL",
    1521: "Oracle", 2049: "NFS", 3306: "MySQL", 3389: "RDP",
    5432: "PostgreSQL", 5900: "VNC", 5985: "WinRM-HTTP",
    5986: "WinRM-HTTPS", 6379: "Redis", 8080: "HTTP-Alt",
    8443: "HTTPS-Alt", 27017: "MongoDB"
}


def resolve_target(target):
    try:
        ip = socket.gethostbyname(target)
        return ip
    except:
        return None


def scan_port(target, port, timeout=1.5):
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(timeout)
        result = sock.connect_ex((target, port))
        if result == 0:
            banner_grab = ""
            try:
                sock.settimeout(2)
                sock.send(b"\r\n")
                banner_grab = sock.recv(1024).decode("utf-8", errors="ignore").strip()
            except:
                pass
            sock.close()
            service = COMMON_PORTS.get(port, "unknown")
            return {
                "port": port,
                "service": service,
                "banner": banner_grab if banner_grab else "No banner"
            }
        sock.close()
    except:
        pass
    return None


def run_scan(target, start_port, end_port, progress_callback=None, stop_flag=None, timeout=1.5):
    ip = resolve_target(target)
    if not ip:
        return None

    results = []
    total = end_port - start_port + 1
    scanned = 0
    start_time = time.time()

    with ThreadPoolExecutor(max_workers=100) as executor:
        futures = {executor.submit(scan_port, ip, p, timeout): p for p in range(start_port, end_port + 1)}
        for future in as_completed(futures):
            if stop_flag and stop_flag():
                break
            scanned += 1
            info = future.result()
            if info:
                results.append(info)
            if progress_callback:
                progress_callback(scanned, total, results)

    elapsed = time.time() - start_time
    return {
        "target": target,
        "ip": ip,
        "start_port": start_port,
        "end_port": end_port,
        "results": results,
        "scanned": scanned,
        "total": total,
        "elapsed": round(elapsed, 2)
    }


def save_results(target, results_list, elapsed):
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"scan_{target.replace('.','_').replace(':','_')}_{timestamp}.txt"
    filepath = os.path.join(os.getcwd(), filename)
    with open(filepath, "w") as f:
        f.write("=" * 60 + "\n")
        f.write(f"  RECONNAISSANCE SCAN REPORT\n")
        f.write(f"  Target: {target}\n")
        f.write(f"  Date:   {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"  Duration: {elapsed:.2f}s\n")
        f.write(f"  Open Ports Found: {len(results_list)}\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"{'PORT':<8} {'SERVICE':<18} {'BANNER'}\n")
        f.write("-" * 60 + "\n")
        for r in results_list:
            banner_text = r["banner"] if r["banner"] and r["banner"] != "No banner" else "-"
            f.write(f"{r['port']:<8} {r['service']:<18} {banner_text}\n")
        f.write("\n" + "=" * 60 + "\n")
        f.write("  Generated by Recon Scanner\n")
        f.write("=" * 60 + "\n")
    return filepath


def read_report(filepath):
    with open(filepath, "r") as f:
        return f.read()
